//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;display&quot;: &quot;wizard&quot;,
        ///	&quot;id&quot;: &quot;1234567890&quot;,
        ///    &quot;components&quot;: [
        ///        {
        ///            &quot;title&quot;: &quot;Page 1&quot;,
        ///            &quot;label&quot;: &quot;Page 1&quot;,
        ///            &quot;type&quot;: &quot;panel&quot;,
        ///            &quot;key&quot;: &quot;page1&quot;,
        ///            &quot;components&quot;: [
        ///				{
        ///                    &quot;label&quot;: &quot;Ids&quot;,
        ///                    &quot;redrawOn&quot;: &quot;data&quot;,
        ///                    &quot;customDefaultValue&quot;: &quot;value = \&quot;0987654321\&quot;&quot;,
        ///                    &quot;calculateServer&quot;: false,
        ///                    &quot;key&quot;: &quot;ids&quot;,
        ///                    &quot;type&quot;: &quot;hidden&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string formData {
            get {
                return ResourceManager.GetString("formData", resourceCulture);
            }
        }
    }
}
